# Generated by Django 3.1.5 on 2021-01-27 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classroom', '0002_classroom_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('total_marks', models.IntegerField(default=0)),
                ('rules', models.CharField(default='Add some exam rules', max_length=100)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('posted_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_exam', to='Classroom.classroom')),
                ('submitted', models.ManyToManyField(blank=True, related_name='submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(choices=[('Exam', 'option1'), ('B', 'option2'), ('C', 'option3'), ('D', 'option4')], max_length=1)),
                ('duration', models.IntegerField(default=0)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtain_marks', models.PositiveIntegerField(default=0)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Exam.exam')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.fields.CharField, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
