# Generated by Django 3.1.7 on 2021-03-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='student_name',
        ),
        migrations.AddField(
            model_name='participants',
            name='student_id',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
