# Generated by Django 3.1.5 on 2021-01-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
