# Generated by Django 3.1.5 on 2021-01-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_auto_20210127_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
