# Generated by Django 3.1.7 on 2021-03-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_auto_20210128_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='duration',
        ),
    ]
