# Generated by Django 3.1.7 on 2021-03-12 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('photo', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.program')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varsity_id', models.IntegerField(unique=True)),
                ('intake', models.IntegerField()),
                ('section', models.IntegerField()),
                ('photo', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.program')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
