//all classroom types
export const GET_INTAKE_CLASSROOM_LIST = 'GET_CLASSROOM';
export const CREATE_CLASSROOMS = 'CREATE_CLASSROOM';
export const GET_MY_CLASSROOM_LIST = 'GET_MY_CLASSROOM';
export const GET_CLASSROOMS = 'GET_CLASSROOMS';
export const GET_EXAM_LIST = 'GET_EXAM_LIST';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const PARTICIPANTS_LIST = 'PARTICIPANTS_LIST';
export const POST_PARTICIPANTS = 'POST_PARTICIPANTS';

export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS';
export const POST_ASSIGNMENT_ANSWER = 'POST_ASSIGNMENT_ANSWER';
export const GET_ASSIGNMENT_ANSWER_LIST = 'GET_ASSIGNMENT_ANSWER_LIST';

export const GET_STREAM = 'GET_STREAM';
export const POST_STREAM = 'POST_STREAM';

export const GET_STREAM_COMMENT = 'GET_STREAM_COMMENT';
export const POST_STREAM_COMMENT = 'POST_STREAM_COMMENT';