//all classroom types
export const GET_CLASSROOM_LIST = 'GET_CLASSROOM';
export const JOIN_CLASSROOM = 'JOIN_CLASSROOM';
export const CREATE_CLASSROOMS = 'CREATE_CLASSROOM';
export const GET_MY_CLASSROOM_LIST = 'GET_MY_CLASSROOM';
export const GET_CLASSROOMS = 'GET_CLASSROOMS';

export const CREATE_EXAM = 'CREATE_EXAM';
export const GET_EXAM_LIST = 'GET_EXAM_LIST';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const EXAM_PARTICIPANTS_LIST = 'PARTICIPANTS_LIST';
export const POST_EXAM_PARTICIPANTS = 'POST_EXAM_PARTICIPANTS';

export const POST_ASSIGNMENT = 'POST_ASSIGNMENT';
export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS';
export const POST_ASSIGNMENT_ANSWER = 'POST_ASSIGNMENT_ANSWER';
export const ASSIGNMENT_PARTICIPANTS_LIST = 'ASSIGNMENT_PARTICIPANTS_LIST';

export const GET_STREAM = 'GET_STREAM';
export const POST_STREAM = 'POST_STREAM';

export const GET_STREAM_COMMENT = 'GET_STREAM_COMMENT';
export const POST_STREAM_COMMENT = 'POST_STREAM_COMMENT';

export const TEACHER_CLASSROOM = 'TEACHER_CLASSROOM';
