//all classroom types
export const GET_INTAKE_CLASSROOM_LIST = 'GET_CLASSROOM';
export const CREATE_CLASSROOMS = 'CREATE_CLASSROOM';
export const GET_MY_CLASSROOM_LIST = 'GET_MY_CLASSROOM';
export const GET_CLASSROOMS = 'GET_CLASSROOMS';
