# Generated by Django 3.1.5 on 2021-02-09 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0002_classroom_intake'),
        ('Stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Classroom.classroom'),
            preserve_default=False,
        ),
    ]
