# Generated by Django 3.1.7 on 2021-03-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stream', '0002_stream_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='title',
        ),
    ]
