# Generated by Django 3.1.5 on 2021-01-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='cover',
            field=models.ImageField(default='BlogHeader.jpg', upload_to='blog_covers'),
        ),
    ]
