# Generated by Django 3.1.7 on 2021-03-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(choices=[('CSE', 'CSE'), ('BBA', 'BBA'), ('EEE', 'EEE'), ('LL.B', 'LL.B'), ('TEXTILE', 'TEXTILE'), ('ENGLISH', 'ENGLISH'), ('ECONOMICS', 'ECONOMICS')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='intake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_name', models.CharField(max_length=50)),
                ('program_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.program')),
            ],
        ),
    ]
