# Generated by Django 3.1.5 on 2021-01-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(choices=[('CSE', 'CSE'), ('BBA', 'BBA'), ('EEE', 'EEE'), ('LL.B', 'LL.B'), ('TEXTILE', 'TEXTILE'), ('ENGLISH', 'ENGLISH'), ('ECONOMICS', 'ECONOMICS')], max_length=20)),
            ],
        ),
    ]
