# Generated by Django 3.1.7 on 2021-03-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_participants',
            name='file_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
